import { useEffect, useMemo, useState } from "react";
import type { AppSettings, ConnectionStatus, ReleaseTrack } from "@ragectrl/shared";
import { api } from "./api"; import { mockStatus, mockTracks } from "./mock";
type Filter = "all" | "single" | "album" | "primary" | "collaboration";
const labels: Record<AppSettings["orderingMode"], string> = { newest:"Newest first", oldest:"Oldest first", random:"Random", keep:"Keep current order" };
const duration = (ms:number) => `${Math.floor(ms/60000)}:${String(Math.floor(ms/1000)%60).padStart(2,"0")}`;
function Header({ connected, onLogout }:{connected:boolean;onLogout:()=>void}) { return <header><div className="brand"><div className="logo">RAGE<br/>CTRL</div><div><p className="eyebrow">PRIVATE PLAYLIST OPERATIONS</p><h1>Playlist Automator</h1></div></div><div className="connection"><span className={connected ? "dot on" : "dot"}/><span>{connected ? "Spotify connected" : "Spotify disconnected"}</span>{connected ? <button className="ghost" onClick={onLogout}>Disconnect</button> : <a className="button" href={api.authUrl}>Connect Spotify</a>}</div></header> }
function Summary({ status }:{status:ConnectionStatus}) { const p=status.playlist; return <section className="summary"><div className="cover">RC</div><div className="playlist"><p className="eyebrow">TARGET PLAYLIST</p><h2>{p.name}</h2><p className="muted">Managed playlist · Spotify</p></div><Metric value={p.trackCount} label="Tracks"/><Metric value={p.pendingCount} label="Pending" accent/><div className="metric"><strong className="date">{p.lastScanAt ? new Date(p.lastScanAt).toLocaleString() : "Never"}</strong><span>Last scan</span></div></section> }
function Metric({value,label,accent=false}:{value:number;label:string;accent?:boolean}) { return <div className="metric"><strong className={accent?"accent":""}>{value}</strong><span>{label}</span></div> }
function TrackCard({track,selected,toggle}:{track:ReleaseTrack;selected:boolean;toggle:()=>void}) { const isPrimary=track.artists.some(a=>track.primaryArtistIds.includes(a.id)); return <article className={`track ${selected?"selected":""}`} onClick={toggle}><input aria-label={`Select ${track.title}`} type="checkbox" checked={selected} onChange={toggle} onClick={e=>e.stopPropagation()}/><div className="art">{track.artworkUrl?<img src={track.artworkUrl} alt=""/>:<span>RC</span>}</div><div className="track-main"><div className="badges"><span className="badge">{track.status}</span><span className="badge subtle">{isPrimary?"PRIMARY ARTIST":"FEATURED ARTIST"}</span></div><h3>{track.title}</h3><p>{track.artists.map(a=>a.name).join(", ")}</p></div><div className="release"><span>{track.albumName}</span><small>{track.albumType.toUpperCase()} · {track.releaseDate}</small></div><div className="duration">{duration(track.durationMs)}</div><a href={track.externalUrl} onClick={e=>e.stopPropagation()} target="_blank" rel="noreferrer" aria-label="Open on Spotify">↗</a></article> }
function Modal({count,playlist,mode,onCancel,onConfirm,busy}:{count:number;playlist:string;mode:AppSettings["orderingMode"];onCancel:()=>void;onConfirm:()=>void;busy:boolean}) { return <div className="modal-backdrop" role="presentation"><div className="modal" role="dialog" aria-modal="true"><p className="eyebrow">CONFIRM PLAYLIST UPDATE</p><h2>Add {count} track{count===1?"":"s"}?</h2><dl><div><dt>Target</dt><dd>{playlist}</dd></div><div><dt>Ordering</dt><dd>{labels[mode]}</dd></div></dl><p className="muted">Tracks already in the playlist will be skipped automatically.</p><div className="modal-actions"><button className="ghost" onClick={onCancel}>Cancel</button><button onClick={onConfirm} disabled={busy}>{busy?"Adding…":"Confirm & add"}</button></div></div></div> }
export function App() { const [status,setStatus]=useState(mockStatus),[tracks,setTracks]=useState<ReleaseTrack[]>(mockTracks),[selected,setSelected]=useState<Set<string>>(new Set()),[filter,setFilter]=useState<Filter>("all"),[busy,setBusy]=useState(false),[modal,setModal]=useState(false),[notice,setNotice]=useState<{kind:"success"|"error";text:string}|null>(null);
  const run=async<T,>(work:()=>Promise<T>,done:(value:T)=>void)=>{setBusy(true);setNotice(null);try{done(await work())}catch(e){setNotice({kind:"error",text:e instanceof Error?e.message:"Unexpected API error"})}finally{setBusy(false)}};
  useEffect(()=>{void run(async()=>({status:await api.status(),tracks:await api.pending()}),v=>{setStatus(v.status);setTracks(v.tracks)})},[]);
  const visible=useMemo(()=>tracks.filter(t=>filter==="all"||filter===t.albumType||(filter==="primary"&&t.artists.some(a=>t.primaryArtistIds.includes(a.id)))||(filter==="collaboration"&&t.artists.some(a=>!t.primaryArtistIds.includes(a.id)))),[tracks,filter]);
  const ids=[...selected]; const toggle=(id:string)=>setSelected(s=>{const n=new Set(s);n.has(id)?n.delete(id):n.add(id);return n});
  const scan=()=>void run(api.scan,v=>{setTracks(v);setSelected(new Set());setNotice({kind:"success",text:`Scan complete — ${v.length} pending tracks.`})});
  const reject=()=>ids.length&&void run(()=>api.reject(ids),v=>{setTracks(t=>t.filter(x=>!selected.has(x.spotifyTrackId)));setSelected(new Set());setNotice({kind:"success",text:`Rejected ${v.rejected} tracks.`})});
  const add=()=>void run(()=>api.add(ids,status.settings.orderingMode),v=>{setTracks(t=>t.filter(x=>!selected.has(x.spotifyTrackId)));setSelected(new Set());setModal(false);setNotice({kind:"success",text:`Added ${v.added}; ${v.alreadyPresent} already present; ${v.failed} failed.`})});
  return <><Header connected={status.connected} onLogout={()=>void run(api.logout,()=>setStatus(s=>({...s,connected:false})))}/><main><Summary status={{...status,playlist:{...status.playlist,pendingCount:tracks.length}}}/>{notice&&<div className={`notice ${notice.kind}`}>{notice.text}<button aria-label="Dismiss" onClick={()=>setNotice(null)}>×</button></div>}<section className="toolbar"><div className="actions"><button onClick={scan} disabled={busy}>{busy?"Working…":"Scan for releases"}</button><button className="ghost" onClick={()=>setSelected(new Set(visible.map(t=>t.spotifyTrackId)))}>Select all</button><button className="ghost" onClick={()=>setSelected(new Set())}>Clear selection</button><button className="danger" disabled={!ids.length} onClick={reject}>Reject selected</button><button disabled={!ids.length} onClick={()=>setModal(true)}>Add selected to playlist <b>{ids.length||""}</b></button></div><div className="order"><label htmlFor="order">PLAYLIST ORDER</label><select id="order" value={status.settings.orderingMode} onChange={e=>setStatus(s=>({...s,settings:{...s.settings,orderingMode:e.target.value as AppSettings["orderingMode"]}}))}>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div></section><nav className="filters" aria-label="Release filters">{(["all","single","album","primary","collaboration"] as Filter[]).map(f=><button className={filter===f?"active":""} onClick={()=>setFilter(f)} key={f}>{f==="single"?"Singles":f==="album"?"Albums":f==="primary"?"Primary artist only":f[0]!.toUpperCase()+f.slice(1)}</button>)}</nav><div className="section-title"><div><p className="eyebrow">RELEASE INBOX</p><h2>Pending releases</h2></div><strong>{visible.length.toString().padStart(2,"0")}</strong></div><section className="tracks">{visible.length?visible.map(t=><TrackCard key={t.spotifyTrackId} track={t} selected={selected.has(t.spotifyTrackId)} toggle={()=>toggle(t.spotifyTrackId)}/>):<div className="empty"><b>INBOX CLEAR</b><p>No unreviewed tracks match this filter. Run a scan to check for new releases.</p></div>}</section></main>{modal&&<Modal count={ids.length} playlist={status.playlist.name} mode={status.settings.orderingMode} onCancel={()=>setModal(false)} onConfirm={add} busy={busy}/>}</> }
